<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.Fonet.XsltTransformer</PackageId>
        <RootNamespace>Genocs.Fonet.XsltTransformer</RootNamespace>
        <AssemblyName>Genocs.Fonet.XsltTransformer</AssemblyName>
        <Title>Genocs Fonet XSLT to PDF Transformer library</Title>
        <Description>Fonet XSLT to PDF Transformer library.</Description>
        <Summary>The library used to transform XML documents using XSLT and generate PDFs.</Summary>
        <PackageTags>genocs fonet xslt transformer pdf</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Genocs.Fonet\Genocs.Fonet.csproj" />
    </ItemGroup>
</Project>
