<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.Fonet</PackageId>
        <RootNamespace>Genocs.Fonet</RootNamespace>
        <AssemblyName>Genocs.Fonet</AssemblyName>
        <Title>Genocs Fonet library</Title>
        <Description>Fonet library to build PDFs by transforming XML documents through XSLT.</Description>
        <Summary>The PDF building library based on Fonet.</Summary>
        <PackageTags>genocs fonet pdf</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="4.153.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.153.1" />
        <PackageReference Include="Svg.Skia" Version="5.2.3" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Genocs.Fonet.UnitTests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Roslynator.Analyzers" Version="5.0.1" />
    </ItemGroup>

</Project>
